name: dobesv
favicon: null
layout_spectrum: 0.9013969132211059
typography_spectrum: 0.33594825002364814
title: 'Dobes Vandermeer - Computer Science, Software Engineering, Personal Development, Philosophy, and more'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-24340079-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#965d1f'
    - '#fafaf8'
    - '#c3a187'
    - '#464a56'
  brandStrength: 0.5
  lightness: 0.6564160641282797
  saturation: 0.5620124354027212
  rhythmicContrast: 0.6260989783331752
purpose: []
